/*

 BG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : C:\gbdk\0_MyProjects\2_learn\bgtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bgWidth 32
#define bgHeight 18
#define bgBank 0

extern unsigned char bg[];

/* End of BG21.H */
